"""Initial migration.

Revision ID: 050f824ed9a5
Revises: e1fa497a8619
Create Date: 2021-06-15 21:46:42.424275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '050f824ed9a5'
down_revision = 'e1fa497a8619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tags',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_tags')
    # ### end Alembic commands ###
